[project]
name = "rbm-tensorflow"
version = "0.1.0"
description = "Restricted Boltzmann Machine (RBM)"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.9.2",
    "tensorflow<2.16",
]
